services:
  db:
    container_name: w1_postgres
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=w1_holdings
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 2s

  api:
    container_name: w1_api
    build: ./back
    ports:
      - "${API_PORT}:80"
    volumes:
      - w1_hackathon:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/w1_holdings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    healthcheck:
      test: curl -f http://localhost:80/healthcheck || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 2s

  redis:
    container_name: w1_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  worker:
    container_name: w1_worker
    build: ./back
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - w1_hackathon:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/w1_holdings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  w1_hackathon:
