services:
  api:
    container_name: api
    build: ./back
    ports:
      - "${API_PORT}:80"
    volumes:
      - ./back:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s