name: Deploy API

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy API Service
    runs-on: self-hosted
    environment: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "API_PORT=${{ secrets.API_PORT }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Stop containers
        run: |
          docker compose down --remove-orphans
        continue-on-error: true

      - name: Prune unused volumes
        run: |
          docker volume prune -f
        continue-on-error: true

      - name: Build and start containers
        run: |
          docker compose up -d --build --force-recreate --remove-orphans --no-deps

      - name: Run healthcheck
        run: |
          for i in $(seq 1 10); do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' w1_api)
            if [ "$STATUS" = "healthy" ]; then
              echo "API está saudável."
              exit 0
            fi
            echo "Aguardando healthcheck… ($i/10)"
            sleep 2
          done
          echo "❌ API container não ficou healthy." >&2
          docker logs w1_api >&2 || true
          exit 1
